import type { Metadata } from "next";
import NavbarElement from "./components/navbar";
import "./globals.scss";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body suppressHydrationWarning={true}>
        <Providers>
          <NavbarElement />
          {children}
        </Providers>
      </body>
    </html>
  );
}
